# -*- coding: utf-8 -*-
"""nlp customer review sentiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yOWtOP7oBJvX5EQHcKb6Q8LHwvZP6Egy
"""

# ============================================================
# NLP CUSTOMER REVIEW SENTIMENT ANALYSIS
# USING TRANSFORMERS (BERT)
# ============================================================

# ======================
# INSTALL REQUIRED LIBRARIES
# ======================

# pip install transformers
# pip install torch
# pip install scikit-learn

# ======================
# IMPORT LIBRARIES
# ======================

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from transformers import pipeline

# ======================
# LOAD DATASET
# ======================

df = pd.read_csv("eda_final_superstore.csv")

# ======================
# CREATE SAMPLE REVIEWS
# (REMOVE THIS SECTION IF YOU HAVE REAL REVIEWS)
# ======================

sample_reviews = [
    "Amazing product and fast delivery",
    "Very bad quality and terrible service",
    "Good value for money",
    "Excellent customer support",
    "The product arrived damaged",
    "Highly recommended product",
    "Worst shopping experience ever",
    "Satisfied with the purchase",
    "Late delivery but good product",
    "Fantastic packaging and quality"
]

# Repeat reviews to match dataset size
df = df.head(len(sample_reviews))

df['Review'] = sample_reviews

# ======================
# LOAD BERT SENTIMENT MODEL
# ======================

sentiment_pipeline = pipeline(
    "sentiment-analysis"
)

# ======================
# PREDICT SENTIMENTS
# ======================

results = sentiment_pipeline(
    df['Review'].tolist()
)

# ======================
# EXTRACT RESULTS
# ======================

df['Sentiment'] = [
    result['label']
    for result in results
]

df['Confidence'] = [
    result['score']
    for result in results
]

# ======================
# DISPLAY RESULTS
# ======================

print("\nSentiment Analysis Results:\n")

print(df[['Review', 'Sentiment', 'Confidence']])

# ======================
# SENTIMENT DISTRIBUTION
# ======================

sentiment_counts = df['Sentiment'].value_counts()

print("\nSentiment Distribution:\n")

print(sentiment_counts)

# ======================
# VISUALIZATION
# ======================

plt.figure(figsize=(8,5))

sns.countplot(
    data=df,
    x='Sentiment'
)

plt.title("Customer Review Sentiment Distribution")

plt.xlabel("Sentiment")
plt.ylabel("Count")

plt.show()

# ======================
# CONFIDENCE DISTRIBUTION
# ======================

plt.figure(figsize=(8,5))

sns.histplot(
    df['Confidence'],
    bins=10,
    kde=True
)

plt.title("Sentiment Confidence Distribution")

plt.xlabel("Confidence Score")

plt.show()

# ======================
# SAVE OUTPUT
# ======================

df.to_csv(
    "customer_sentiment_analysis.csv",
    index=False
)

print("\nNLP Sentiment Analysis Completed Successfully.")