# -*- coding: utf-8 -*-
"""RANDOM FOREST REGRESSOR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g7bD86Z3Cj7nQ3o7muAiv2Q3qI91jpg_
"""

# ============================================================
# ADVANCED CUSTOMER LIFETIME VALUE (CLV) PREDICTION
# USING RANDOM FOREST REGRESSOR
# ERROR-FREE COMPLETE VERSION
# ============================================================

# ======================
# IMPORT LIBRARIES
# ======================

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

# ======================
# LOAD DATASET
# ======================

df = pd.read_csv("eda_final_superstore.csv")

# ======================
# CLEAN COLUMN NAMES
# ======================

df.columns = df.columns.str.strip()

print("\nDataset Loaded Successfully\n")

print("Columns in Dataset:\n")
print(df.columns.tolist())

# ======================
# CHECK REQUIRED COLUMNS
# ======================

# Note: Original code checks for Profit, Quantity, Discount which are not in the dataset.
# The aggregation and CLV calculation below have been adjusted to reflect available columns.
required_columns = [
    'Order Date',
    'Customer Name',
    'Sales',
    # 'Profit', # Missing from dataset
    # 'Quantity', # Missing from dataset
    # 'Discount', # Missing from dataset
    'Order ID',
    'Region',
    'Segment'
]

missing_cols = [
    col for col in required_columns
    if col not in df.columns
]

if len(missing_cols) > 0:
    print("\nWARNING: Some required columns are missing and will not be used in aggregation/CLV calculation ->", missing_cols)
    # exit() # Commented out to allow code to run with available columns

# ======================
# DATE PROCESSING
# ======================

df['Order Date'] = pd.to_datetime(
    df['Order Date'],
    errors='coerce'
)

# Remove invalid dates
df = df.dropna(subset=['Order Date'])

# ======================
# CREATE RFM FEATURES
# ======================

today = df['Order Date'].max()

rfm = df.groupby('Customer Name').agg({
    'Order Date': lambda x: (today - x.max()).days,
    'Order ID': 'count',
    'Sales': 'sum'
}).reset_index()

rfm.columns = [
    'Customer_Name',
    'Recency',
    'Frequency',
    'Monetary'
]

# ======================
# CREATE CUSTOMER FEATURES
# (Adjusted to use available columns only)
# ======================

customer_df = df.groupby('Customer Name').agg({
    'Sales': 'sum',
    # 'Profit': 'sum',  # Removed: Column missing
    # 'Quantity': 'sum',  # Removed: Column missing
    # 'Discount': 'mean',  # Removed: Column missing
    'Order ID': 'count',
    'Region': lambda x: x.mode()[0],
    'Segment': lambda x: x.mode()[0]
}).reset_index()

# ======================
# RENAME COLUMNS
# (Adjusted to match new aggregation)
# ======================

customer_df.columns = [
    'Customer_Name',
    'Total_Sales',
    'Total_Orders',
    'Region',
    'Segment'
]

# ======================
# MERGE RFM FEATURES
# ======================

customer_df = pd.merge(
    customer_df,
    rfm,
    on='Customer_Name',
    how='left'
)

# ======================
# CREATE CLV TARGET
# (Adjusted due to removal of 'Profit' column)
# ======================

customer_df['CLV'] = (
    customer_df['Total_Sales'] * 0.6 +
    # customer_df['Total_Profit'] * 0.3 + # Removed: Column no longer available
    customer_df['Total_Orders'] * 50
)

# ======================
# ONE-HOT ENCODING
# ======================

customer_df = pd.get_dummies(
    customer_df,
    columns=['Region', 'Segment'],
    drop_first=True
)

# ======================
# FEATURE SELECTION
# ======================

X = customer_df.drop(
    columns=[
        'Customer_Name',
        'CLV'
    ]
)

y = customer_df['CLV']

# ======================
# TRAIN TEST SPLIT
# ======================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# ======================
# BUILD MODEL
# ======================

model = RandomForestRegressor(
    n_estimators=300,
    max_depth=10,
    random_state=42
)

# ======================
# TRAIN MODEL
# ======================

print("\nTraining Model...\n")

model.fit(X_train, y_train)

# ======================
# PREDICTIONS
# ======================

y_pred = model.predict(X_test)

# ======================
# EVALUATION
# ======================

mae = mean_absolute_error(y_test, y_pred)

mse = mean_squared_error(y_test, y_pred)

rmse = np.sqrt(mse)

r2 = r2_score(y_test, y_pred)

print("\n==============================")
print("CLV MODEL PERFORMANCE")
print("==============================\n")

print(f"MAE  : {mae:.2f}")
print(f"MSE  : {mse:.2f}")
print(f"RMSE : {rmse:.2f}")
print(f"R2   : {r2:.4f}")

# ======================
# FEATURE IMPORTANCE
# ======================

importance_df = pd.DataFrame({
    'Feature': X.columns,
    'Importance': model.feature_importances_
})

importance_df = importance_df.sort_values(
    by='Importance',
    ascending=False
)

print("\n==============================")
print("FEATURE IMPORTANCE")
print("==============================\n")

print(importance_df)

# ======================
# FEATURE IMPORTANCE PLOT
# ======================

plt.figure(figsize=(10, 6))

sns.barplot(
    data=importance_df,
    x='Importance',
    y='Feature'
)

plt.title("Feature Importance for CLV Prediction")

plt.tight_layout()

plt.show()

# ======================
# ACTUAL VS PREDICTED
# ======================

plt.figure(figsize=(8, 6))

plt.scatter(
    y_test,
    y_pred,
    alpha=0.6
)

plt.xlabel("Actual CLV")

plt.ylabel("Predicted CLV")

plt.title("Actual vs Predicted CLV")

plt.tight_layout()

plt.show()

# ======================
# CORRELATION HEATMAP
# ======================

plt.figure(figsize=(12, 8))

sns.heatmap(
    customer_df.corr(numeric_only=True),
    annot=True,
    cmap='coolwarm'
)

plt.title("Correlation Matrix")

plt.tight_layout()

plt.show()

# ======================
# RESIDUAL DISTRIBUTION
# ======================

residuals = y_test - y_pred

plt.figure(figsize=(8, 6))

sns.histplot(
    residuals,
    kde=True
)

plt.title("Residual Distribution")

plt.xlabel("Prediction Error")

plt.tight_layout()

plt.show()

# ======================
# CUSTOMER SEGMENTATION
# ======================

customer_df['Predicted_CLV'] = model.predict(X)

customer_df['Customer_Level'] = pd.qcut(
    customer_df['Predicted_CLV'],
    q=4,
    labels=[
        'Low Value',
        'Medium Value',
        'High Value',
        'VIP Customer'
    ]
)

# ======================
# TOP CUSTOMERS
# ======================

top_customers = customer_df.sort_values(
    by='Predicted_CLV',
    ascending=False
).head(10)

print("\n==============================")
print("TOP VIP CUSTOMERS")
print("==============================\n")

print(top_customers[[
    'Customer_Name',
    'Predicted_CLV',
    'Customer_Level'
]])

# ======================
# SAVE RESULTS
# ======================

customer_df.to_csv(
    "customer_clv_predictions.csv",
    index=False
)

print("\nCustomer Lifetime Value Prediction Completed Successfully.\n")