# -*- coding: utf-8 -*-
"""EXPLAINABLE AI USING SHAP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OKBgXsth8wkXLHvBfZUTpG_xC_OG4w7e
"""

# ============================================================
# EXPLAINABLE AI USING SHAP
# XGBOOST MODEL INTERPRETATION
# ============================================================

# ======================
# INSTALL REQUIRED LIBRARIES
# ======================

# pip install shap
# pip install xgboost

# ======================
# IMPORT LIBRARIES
# ======================

import pandas as pd
import numpy as np

import shap

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from xgboost import XGBRegressor

# ======================
# LOAD DATASET
# ======================

df = pd.read_csv("eda_final_superstore.csv")

# ======================
# DATE FEATURES
# ======================

df['Order Date'] = pd.to_datetime(df['Order Date'])

df['Year'] = df['Order Date'].dt.year
df['Month'] = df['Order Date'].dt.month
df['Day'] = df['Order Date'].dt.day

# ======================
# ENCODE CATEGORICAL DATA
# ======================

categorical_cols = [
    'Category',
    'Sub-Category',
    'Region',
    'Segment'
]

encoder = LabelEncoder()

for col in categorical_cols:
    df[col] = encoder.fit_transform(df[col])

# ======================
# FEATURES & TARGET
# ======================

desired_X_cols = [
    'Quantity',
    'Discount',
    'Profit',
    'Category',
    'Sub-Category',
    'Region',
    'Segment',
    'Year',
    'Month',
    'Day'
]

# Filter desired columns to only include those present in the DataFrame
X_cols = [col for col in desired_X_cols if col in df.columns]

X = df[X_cols]
y = df['Sales']

# ======================
# TRAIN TEST SPLIT
# ======================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# ======================
# TRAIN XGBOOST MODEL
# ======================

model = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=8,
    random_state=42
)

model.fit(X_train, y_train)

# ======================
# CREATE SHAP EXPLAINER
# ======================

explainer = shap.Explainer(model)

shap_values = explainer(X_test)

# ======================
# SHAP SUMMARY PLOT
# ======================

shap.summary_plot(
    shap_values,
    X_test
)

# ======================
# FEATURE IMPORTANCE
# ======================

shap.plots.bar(shap_values)

# ======================
# WATERFALL PLOT
# SINGLE PREDICTION EXPLANATION
# ======================

shap.plots.waterfall(
    shap_values[0]
)

# ======================
# DEPENDENCE PLOT
# ======================

shap.dependence_plot(
    "Year", # Changed from "Profit" to "Year" as 'Profit' is not in X_test
    shap_values.values,
    X_test
)

print("\nSHAP Explainable AI Completed Successfully.")