# -*- coding: utf-8 -*-
"""Complete including LASTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CiNeBnQQ55PsGQrljggcl3dbuLGlqRZ3
"""

import pandas as pd

df = pd.read_csv("eda_final_superstore.csv")

print(df.head())
print("\nDataFrame columns:", df.columns.tolist()) # Added to show all columns

# The original error was that 'Quantity', 'Discount', 'Profit' were not found in the DataFrame columns.
# We need to select existing columns for X and define a target variable y.
# Let's assume 'Customer Total Sales' is the target (y) and 'Customer Order Count' is a feature (X).
# Please adjust X and y based on the actual columns and your modeling goal.

X = df[['Customer Order Count']] # Example: Using 'Customer Order Count' as a feature
y = df['Customer Total Sales'] # Example: Using 'Customer Total Sales' as the target

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print(y_pred[:5])

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

mae = mean_absolute_error(y_test, y_pred)

mse = mean_squared_error(y_test, y_pred)

r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("R2 Score:", r2)

# ============================================================
# CUSTOMER SEGMENTATION USING K-MEANS CLUSTERING
# ============================================================

# ======================
# IMPORT LIBRARIES
# ======================

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# ======================
# LOAD DATASET
# ======================

df = pd.read_csv("eda_final_superstore.csv") # Corrected filename from 'eda_final_superstore(1).csv'

# ======================
# CREATE CUSTOMER FEATURES
# ======================

# Removed 'Profit', 'Quantity', 'Discount' as they were not found in df.columns.tolist()
customer_data = df.groupby("Customer Name").agg({
    "Sales": "sum",
    "Order ID": "count" # Using Order ID count as a proxy for Total_Orders
}).reset_index()

# Rename columns
customer_data.columns = [
    "Customer_Name",
    "Total_Sales",
    "Total_Orders"
]

# ======================
# SELECT FEATURES
# ======================

X = customer_data[[
    "Total_Sales",
    "Total_Orders"
]]

# ======================
# FEATURE SCALING
# ======================

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

# ======================
# FIND OPTIMAL CLUSTERS
# ELBOW METHOD
# ======================

wcss = []

for i in range(1, 11):

    kmeans = KMeans(
        n_clusters=i,
        init='k-means++',
        random_state=42,
        n_init=10
    )

    kmeans.fit(X_scaled)

    wcss.append(kmeans.inertia_)

# Plot Elbow Graph

plt.figure(figsize=(10,5))

plt.plot(range(1,11), wcss, marker='o')

plt.title("Elbow Method")
plt.xlabel("Number of Clusters")
plt.ylabel("WCSS")

plt.show()

# ======================
# TRAIN K-MEANS MODEL
# ======================

kmeans = KMeans(
    n_clusters=4,
    init='k-means++',
    random_state=42,
    n_init=10
)

customer_data['Cluster'] = kmeans.fit_predict(X_scaled)

# ======================
# VIEW CLUSTERS
# ======================

print(customer_data.head())

# ======================
# CLUSTER SUMMARY
# ======================

cluster_summary = customer_data.groupby("Cluster").mean(numeric_only=True)

print("\nCluster Summary:\n")
print(cluster_summary)

# ======================
# VISUALIZE CLUSTERS
# ======================

plt.figure(figsize=(12,6))

sns.scatterplot(
    data=customer_data,
    x='Total_Sales',
    y='Total_Orders', # Changed from Total_Profit as it was not present
    hue='Cluster',
    palette='Set1',
    s=100
)

plt.title("Customer Segmentation")
plt.xlabel("Total Sales")
plt.ylabel("Total Orders") # Changed from Total Profit

plt.show()

# ======================
# SAVE OUTPUT
# ======================

customer_data.to_csv(
    "customer_segments.csv",
    index=False
)

print("\nCustomer Segmentation Completed Successfully.")

# ============================================================
# PRODUCT RECOMMENDATION SYSTEM
# COLLABORATIVE FILTERING
# ============================================================

# ======================
# IMPORT LIBRARIES
# ======================

import pandas as pd
import numpy as np

from sklearn.metrics.pairwise import cosine_similarity

# ======================
# LOAD DATASET
# ======================

df = pd.read_csv("eda_final_superstore.csv") # Corrected filename

# ======================
# CREATE CUSTOMER-PRODUCT MATRIX
# ======================

customer_product_matrix = pd.pivot_table(
    df,
    index='Customer Name',
    columns='Product Name',
    values='Sales',
    aggfunc='sum',
    fill_value=0
)

# ======================
# COMPUTE COSINE SIMILARITY
# ======================

similarity_matrix = cosine_similarity(customer_product_matrix)

similarity_df = pd.DataFrame(
    similarity_matrix,
    index=customer_product_matrix.index,
    columns=customer_product_matrix.index
)

# ======================
# RECOMMENDATION FUNCTION
# ======================

def recommend_products(customer_name, top_n=5):

    # Find similar customers
    similar_customers = similarity_df[customer_name].sort_values(
        ascending=False
    )[1:6]

    similar_customer_names = similar_customers.index

    # Products already purchased
    purchased_products = customer_product_matrix.loc[
        customer_name
    ]

    purchased_products = purchased_products[
        purchased_products > 0
    ].index.tolist()

    # Products from similar customers
    recommended_products = []

    for sim_customer in similar_customer_names:

        sim_products = customer_product_matrix.loc[
            sim_customer
        ]

        sim_products = sim_products[
            sim_products > 0
        ].index.tolist()

        for product in sim_products:

            if product not in purchased_products:
                recommended_products.append(product)

    # Remove duplicates
    recommended_products = list(dict.fromkeys(
        recommended_products
    ))

    return recommended_products[:top_n]

# ======================
# TEST RECOMMENDATIONS
# ======================

sample_customer = customer_product_matrix.index[0]

print("\nSample Customer:")
print(sample_customer)

recommendations = recommend_products(sample_customer)

print("\nRecommended Products:")

for i, product in enumerate(recommendations, start=1):
    print(f"{i}. {product}")

# ======================
# SAVE SIMILARITY MATRIX
# ======================

similarity_df.to_csv(
    "customer_similarity_matrix.csv"
)

print("\nRecommendation System Completed Successfully.")

# ============================================================
# SALES FORECASTING USING LSTM (DEEP LEARNING)
# ============================================================

# ======================
# INSTALL REQUIRED LIBRARIES
# ======================

# pip install tensorflow
# pip install scikit-learn

# ======================
# IMPORT LIBRARIES
# ======================

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout

# ======================
# LOAD DATASET
# ======================

df = pd.read_csv("eda_final_superstore.csv")

# ======================
# DATE PROCESSING
# ======================

df['Order Date'] = pd.to_datetime(df['Order Date'])

# ======================
# MONTHLY SALES
# ======================

monthly_sales = df.groupby(
    pd.Grouper(key='Order Date', freq='M')
)['Sales'].sum().reset_index()

# ======================
# PREPARE DATA
# ======================

sales_data = monthly_sales['Sales'].values.reshape(-1,1)

# ======================
# NORMALIZATION
# ======================

scaler = MinMaxScaler(feature_range=(0,1))

scaled_data = scaler.fit_transform(sales_data)

# ======================
# CREATE SEQUENCES
# ======================

X = []
y = []

sequence_length = 3

for i in range(sequence_length, len(scaled_data)):

    X.append(scaled_data[i-sequence_length:i, 0])

    y.append(scaled_data[i, 0])

X = np.array(X)
y = np.array(y)

# ======================
# RESHAPE FOR LSTM
# ======================

X = np.reshape(
    X,
    (X.shape[0], X.shape[1], 1)
)

# ======================
# TRAIN TEST SPLIT
# ======================

split = int(len(X) * 0.8)

X_train = X[:split]
X_test = X[split:]

y_train = y[:split]
y_test = y[split:]

# ======================
# BUILD LSTM MODEL
# ======================

model = Sequential()

model.add(
    LSTM(
        units=64,
        return_sequences=True,
        input_shape=(X_train.shape[1],1)
    )
)

model.add(Dropout(0.2))

model.add(
    LSTM(
        units=64
    )
)

model.add(Dropout(0.2))

model.add(Dense(1))

# ======================
# COMPILE MODEL
# ======================

model.compile(
    optimizer='adam',
    loss='mean_squared_error'
)

# ======================
# TRAIN MODEL
# ======================

history = model.fit(
    X_train,
    y_train,
    epochs=50,
    batch_size=4,
    validation_data=(X_test, y_test),
    verbose=1
)

# ======================
# PREDICTIONS
# ======================

predictions = model.predict(X_test)

# ======================
# INVERSE TRANSFORM
# ======================

predictions = scaler.inverse_transform(predictions.reshape(-1,1))

y_test_actual = scaler.inverse_transform(
    y_test.reshape(-1,1)
)

# ======================
# VISUALIZATION
# ======================

plt.figure(figsize=(12,6))

plt.plot(
    y_test_actual,
    label='Actual Sales'
)

plt.plot(
    predictions,
    label='Predicted Sales'
)

plt.title("LSTM Sales Forecasting")
plt.xlabel("Time")
plt.ylabel("Sales")

plt.legend()

plt.show()

# ======================
# FUTURE FORECAST
# ======================

last_sequence = scaled_data[-sequence_length:]

future_forecast = []

current_sequence = last_sequence

for _ in range(6):

    current_sequence_reshaped = np.reshape(
        current_sequence,
        (1, sequence_length, 1)
    )

    next_prediction = model.predict(
        current_sequence_reshaped,
        verbose=0
    )

    future_forecast.append(next_prediction[0,0])

    current_sequence = np.append(
        current_sequence[1:],
        next_prediction
    )

future_forecast = np.array(future_forecast).reshape(-1,1)

future_forecast = scaler.inverse_transform(
    future_forecast
)

# ======================
# DISPLAY FORECAST
# ======================

print("\nFuture Sales Forecast:\n")

for i, value in enumerate(future_forecast, start=1):

    print(f"Month {i}: {value[0]:.2f}")

# ======================
# SAVE FORECAST
# ======================

forecast_df = pd.DataFrame({
    'Forecast_Month': range(1,7),
    'Predicted_Sales': future_forecast.flatten()
})

forecast_df.to_csv(
    "sales_forecast.csv",
    index=False
)

print("\nLSTM Sales Forecasting Completed Successfully.")